### PR TITLE
Add Zstd library

### PR DESCRIPTION
**Pull request by sfan5**

### CODE REVIEW

**Comment by lhofhansl** [comment]
Looks like the build-failure is transient.

**Comment by lhofhansl** [comment]
@sfan5 Why do the libraries (.a) and includes be checked in separately instead of being built and extracted from the FB tar?

**Comment by sfan5** [comment]
That's how this repository works. It contains the libraries prebuilt and scripts to update them for manual use.
This is not a good approach but I won't be dedicating time to it now.

Also yes, the build failure is irrelevant.

**Comment by lhofhansl** [comment]
LGTM

**Review by nerzhul — APPROVED** [review]

**Comment by lhofhansl** [comment]
Let's merge? (so that we can get a zstd test run on Android)

**Pull request merged**
